<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>interaction_skills</name>
  <version>1.4.0</version>
  <description>Interfaces for PAL interaction skills</description>
  <maintainer email="luka.juricic@pal-robotics.com">user</maintainer>
  <license>Apache License 2.0</license>
  <author email="luka.juricic@pal-robotics.com">Luka Juricic</author>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <depend>action_msgs</depend>
  <depend>builtin_interfaces</depend>
  <depend>std_skills</depend>
  <depend>hri_msgs</depend>
  <depend>geometry_msgs</depend>

  <exec_depend>rosidl_default_runtime</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>ament_cmake_archlint</test_depend>

  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
    <skill content-type="json">
      {
        "id": "ask_human_for_help",
        "description": "Ask a human for help",
        "interface": "action",
        "default_interface_path": "/skill/ask_human_for_help",
        "datatype": "interaction_skills/action/AskHumanForHelp",
        "parameters": {
            "in": [
              {
                  "name": "question_to_human",
                  "type": "string",
                  "required": true,
                  "description": "The question to ask to the human."
              },
              {
                  "name": "person_id",
                  "type": "string array",
                  "description": "The preferred person IDs to ask for help. Those humans will be prioritized when asking for help. If left empty, all tracked humans are considered."
              }
          ]},
        "functional_domains": ["interaction", "communication"]
      }
    </skill>
    <skill content-type="yaml">
    id: do_led_effect
    description: Perform light effects using the robot's LEDs.
    interface: action
    default_interface_path: /skill/do_led_effect
    datatype: interaction_skills/action/DoLedEffect
    functional_domains:
        - interaction
    parameters:
          in:
            - name: groups
              type: string array
              default: []
              description: |
                The LED groups to use for the effect. Available LED groups can be listed from ...[add parameter]
                An empty list means the effect is applied to all LED groups.
            - name: effect
              type: string
              default: solid_color
              description: |
                The selected LED effect, one of:
                - ``solid_color``:
                  Applies up to two solid colors side-by-side to the specified LED groups,
                  with the primary color applied to the first partition of the LED group,
                  and the secondary color applied to the second partition.
                - ``rainbow``: 
                  Lights the LED groups in a rainbow effect,
                  which moves through the LED group cyclically.
                - ``fade``:
                  Fades between two colors cyclically.
                  It starts with the primary color,
                  fades to the secondary color over the first partition,
                  then fades back to the primary color over the second partition.
                - ``blink``:
                  Blinks the LED groups between two colors.
                  It applies a solid primary color in the first partition of a cycle,
                  then applies a solid secondary color in the second partition.
                - ``flow``:
                  Displays a loading-like effect,
                  with the partition ratio of LEDs colored with the primary color moving through the LED group,
                  at a constant speed such to traverse the entire LED group in one cycle,
                  and the secondary color filling the rest of the LED group. 
            - name: duration
              type: float
              default: 0.0
              description: |
                Total duration of the effect before the action is completed.
                A null or negative number will mean the action continues indefinitely until canceled.
            - name: color
              type: :msg:`interaction_skills/msg/Color`
              description: |
                The primary color for the effect.
                Ignored for the ``rainbow`` effect.
            - name: secondary_color
              type: :msg:`interaction_skills/msg/Color`
              description: |
                The secondary color for the effect.
                Ignored for the ``rainbow`` effect.
            - name: cycle
              type: float
              default: 1.0
              description: |
                Duration in seconds of a single cycle of the effect.
                Ignored for the ``solid_color`` effect.
            - name: partition
              type: float
              default: 1.0
              description: |
                For effects with two phases in a cycle
                (or two spatially separated partitions as in ``solid_color``),
                the proportion of the first one ([0., 1.])
                Ignored for the ``rainbow`` effect.
    </skill>
    <skill content-type="json">
      {
        "id": "look_for_human",
        "description": "Search and localize specific humans",
        "interface": "action",
        "default_interface_path": "/skill/look_for_human",
        "datatype": "interaction_skills/action/LookFor",
        "parameters": {
            "in": [
              {
                "name": "patterns",
                "type": "string array",
                "default": [],
                "description": "List of RDF patterns that identify the human to look for. Exactly one variable is expected in the patterns. If left empty, all visible humans are returned."
              }
        ]},
        "functional_domains": ["interaction"]
      }
    </skill>
    <skill content-type="json">
      {
        "id": "look_for_object",
        "description": "Search and localize specific objects",
        "interface": "action",
        "default_interface_path": "/skill/look_for_object",
        "datatype": "interaction_skills/action/LookFor",
        "parameters": {
          "in": [
            {
              "name": "patterns",
              "type": "string array",
              "default": [],
              "description": "List of RDF patterns that identify the objects to look for. Exactly one variable is expected in the patterns."
            }
        ]},
        "functional_domains": ["interaction"]
      }
    </skill>
    <skill content-type="yaml">
    id: set_expression
    description: |
      Sets the expression of the robot. This might include changing the robot's face, body posture, or other expressive features.

      One either sets the expression by name, or by specifying the valence and arousal of the expression.
    interface: topic
    default_interface_path: /skill/set_expression
    datatype: interaction_skills/msg/SetExpression
    functional_domains:
        - interaction
    parameters:
          in:
            - name: expression.expression
              type: string
              description: |
                Name of the expression. See :ref:`list_eyes_expressions` for details.

                One of:

                - neutral
                - angry
                - sad
                - happy
                - surprised
                - disgusted
                - scared
                - pleading
                - vulnerable
                - despaired
                - guilty
                - disappointed
                - embarrassed
                - horrified
                - skeptical
                - annoyed
                - furious
                - suspicious
                - rejected
                - bored
                - tired
                - asleep
                - confused
                - amazed
                - excited
            - name: expression.valence
              type: float
              description: |
                The desired valence of the expression, ranging from -1 (very negative) to 1 (very positive).
            - name: expression.arousal
              type: float
              description: |
                The desired arousal of the expression, ranging from -1 (very calm) to 1 (very excited).
    </skill>
    <skill content-type="yaml">
    id: look_at
    description: |
      Defines the gazing direction of the robot. This skill can be used to either look at a specific point 
      in space (a ROS :term:`tf frame`), or to set a generic gaze policy, such as looking at
      people around the robot.

      Using the ``glance`` policy, you can also use this skill to brielfy look at
      a specific point in space, before returning to the previous gaze policy.

    interface: action
    default_interface_path: /skill/look_at
    datatype: interaction_skills/action/LookAt
    functional_domains:
        - interaction
    parameters:
          in:
            - name: policy
              type: string
              description: |
                One of the policies below, or empty string (in that case, the
                robot will look atpoint in space specified with the ``target`` parameter).

                Available policies:

                - ``random``: randomly look around, with short fixations
                - ``social``: look around for faces, with fixations on detected faces
                - ``glance``: glance at a specific point in space, then return
                  to the previous gaze policy. ``target`` must be specified.
                - ``auto``: automatic gaze policy, implementation-dependent.
                  On PAL interactive robots, equivalent to ``social``.
                - ``reset``: reset the gaze of the robot to looking straight.

            - name: target
              type: :msg:`geometry_msgs/msg/PointStamped`
              description: |
                :term:`tf frame` to track. Ignored if the ``policy`` parameter
                is set to one of the predefined policies.
    </skill>
  </export>
</package>
